name = "Pythia"
uuid = "7cdaf598-12e2-40e7-a2cf-eaf488121ec4"
authors = ["Andrii Babii <babii.andrii@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
